name: Bug Report
description: Report a bug or issue with Swift Craft Launcher
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us quickly identify and fix the issue.
        
        **Before submitting, please make sure:**
        - You are using the latest version of Swift Craft Launcher
        - You have searched existing Issues to confirm this isn't a duplicate
        - You have tried restarting the launcher and game
  
  - type: input
    id: contact
    attributes:
      label: Contact Details (Optional)
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
      
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Clearly describe what happened...
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: Describe what should happen normally...
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the issue
      placeholder: |
        1. Open Swift Craft Launcher
        2. Click on '...'
        3. See error
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: input
    id: launcher-version
    attributes:
      label: Launcher Version
      description: |
        Which version of Swift Craft Launcher are you using? 
        You can find this in the launcher's title bar or About section.
        Latest: 0.1.6-beta
      placeholder: e.g. 0.1.6-beta, 0.1.5-beta, or commit hash for development builds
    validations:
      required: true
      
  - type: dropdown
    id: mac-architecture
    attributes:
      label: Mac Architecture
      description: Which Mac architecture are you using?
      multiple: false
      options:
        - Apple Silicon (M1/M2/M3/M4)
        - Intel (x86_64)
        - Unknown (check About This Mac)
    validations:
      required: true
      
  - type: dropdown
    id: macos-version
    attributes:
      label: macOS Version
      description: Which version of macOS are you running?
      options:
        - macOS Sequoia 26 
        - macOS Sequoia 15.x (Latest)
        - macOS Sonoma 14.x
        - Other (please specify)
    validations:
      required: true
      

  - type: dropdown
    id: modloader
    attributes:
      label: Mod Loader
      description: Which mod loader are you using?
      options:
        - Forge
        - Fabric
        - Quilt
        - NeoForge
        - Vanilla (No Mods)
        - Other
    validations:
      required: true

  - type: textarea
    id: launcher-logs
    attributes:
      label: Launcher Logs
      description: Please paste relevant launcher log output. Can be found in the launcher's log window or log files.
      placeholder: Paste launcher log content here...
      render: shell
    validations:
      required: false
      
  - type: textarea
    id: game-logs
    attributes:
      label: Game Logs (if applicable)
      description: If the issue is related to game execution, please paste the game's latest.log or crash report
      placeholder: Paste game logs or crash reports here...
      render: shell
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, such as screenshots, video links, etc.
      placeholder: Any other useful information...
    validations:
      required: false
      
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing Issues to confirm this is not a duplicate report
          required: true
        - label: I have tried restarting the launcher and game
          required: true
        - label: I am using the latest version of the launcher (or have specified the exact version)
          required: true
        - label: I have provided enough information to reproduce this issue
          required: true
